name: "Tests"

on:
  pull_request:
  push:

jobs:
  tests:
    name: "Test"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: actions/setup-python@v4
        with:
          python-version: "pypy-3.8"
      - run: |
          pip install cryptography>=40
          python -c "from cryptography.hazmat.backends.openssl.backend import backend"
