name: "Tests"

on:
  pull_request:
  push:

jobs:
  tests:
    name: "Test"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: actions/setup-python@v4
        with:
          python-version: "pypy3.7-v7.3.9"
      - name: Test
        run: |
          set -eux
          pip install .
          python -c "from cryptography.hazmat.backends.openssl.backend import backend"
